### ISSUE TITLE
putup --pre-commit: generates file with old version and deprecated hooks? 

### ISSUE THREAD

**Issue by c-bg** [pyscaffold/pyscaffold#288]
Thanks much for creating this awesome project. 
I think I might have witnessed a bug for the defautl `.yaml` config of `pre-commit` details below. 
## The problem
```
putup --pre-commit example
```
results in a `.pre-commit-config.yaml` file with the following content: 

```yaml
exclude: '^docs/conf.py'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3 # "BUG": v3.1.0 would be the latest one
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']
  - id: flake8 # "BUG": this hook was removed
    args: ['--max-line-length=88']  # default of Black

- repo: https://github.com/pre-commit/mirrors-isort # "BUG": deprecated
  rev: v4.3.4
  hooks:
  - id: isort
```

As inserted above in comments, the most recent version for `pre-commit-hooks` would be 3.1.0 and https://github.com/pre-commit/mirrors-isort is officially deprecated. Also, `flake8` was removed according to the pre-commit website: https://pre-commit.com/hooks.html

The current state of the pyscaffold repo contains a [more up-to-date config](https://github.com/pyscaffold/pyscaffold/blob/master/.pre-commit-config.yaml), however it still includes the deprecated https://github.com/pre-commit/mirrors-isort repo. 

## Versions and main components

* PyScaffold Version: 3.2.3
* Python Version: 3.8.2
* How did you install PyScaffold: pip
