### ISSUE TITLE
Support PEP 561 - Typing Support

### ISSUE THREAD

**Issue by CarliJoy** [pyscaffold/pyscaffold#447]
## Describe your use-case
Newer MyPy Version require packages to support [PEP 561](https://www.python.org/dev/peps/pep-0561/) to be considered typed.
It would be great if there is switch to enable typing support for pyscaffold
Next to supporting PEP 561 it would be great if i.e. tox / CI/CD scripts will include also a stage for type checking with mypy

## Describe the solution you would like to see for your use-case
Adding a switch `--typed` that will at least create the `py.typed` file in the `src` folder.
Next to this also the .tox configuration is adopted.

Do you see such a switch within pyscaffold or more within an extension?
Including it within the default pyscaffold will allow other extension writers i.e. of CI/CD scripts to also adopt their pipelines accordingly.

**Comment by abravalheri** [comment]
Hi @CarliJoy, thank you very much for the info... I was really not away that mypy started requiring `py.typed` to be present.

I think for this particular issue, making it an internal implementation might make more sense (this way other extensions could check a `typed: bool` flag in options and also generate typed files...). But we can discuss that, as always there are pros and cons.

For the sake of brainstorm, these are a few snippets that can be useful when implementing this feature (taken from a [PR](https://github.com/pyscaffold/configupdater/pull/23/files) I made to `configupdater`):

```ini
# tox.ini

[testenv:typecheck]
description = invoke mypy to typecheck the source code
changedir = {toxinidir}
passenv =
    TERM
    # ^ ensure colors
deps =
    mypy
commands =
    python -m mypy src
```

```ini
# mypy configuration (setup.cfg)

[mypy]
pretty = True
show_error_codes = True
show_error_context = True
show_traceback = True
ignore_missing_imports = True
warn_redundant_casts = True
warn_unused_ignores = True
```

```yaml
# .cirrus.yml

typecheck_task:
  name: typecheck (Linux - 3.9)
  container: {image: "python:3.9-buster"}  # most recent => better type support
  pip_cache: *pip-cache
  mypy_cache:
    folder: .mypy_cache
  install_script: &debian-install
    - apt-get install -y git
  mypy_install_script:
    - python -m pip install --upgrade pip setuptools mypy -e .
  typecheck_script:
    - python -m mypy src
```

My question is: from the user perspective, when someone uses `--typed`, would they expect all the existing extensions to generate typed code? (e.g. when using `pyscaffoldext-django`, `pyscaffoldext-dsproject`, etc?)
