### ISSUE TITLE
Errors reported in new/empty project by common linting tools

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [pyscaffold/pyscaffold#741]
## Versions and main components

* PyScaffold Version: 4.5
* Python Version: N/A
* Operating system: macOS (not relevant)
* How did you install PyScaffold: pip

## How to recreate

1. Create a new project with default settings.
2. Implement the attached .pre-commit-config.yaml in the new project folder
3. Lint the project files with: pre-commit run -a

## Errors reported:

```
python tests naming......................................................Failed
- hook id: name-tests-test
- exit code: 1

tests/test_skeleton.py does not match pattern ".*_test\.py"

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted src/osc_data_extractor/__init__.py

All done! ✨ 🍰 ✨
1 file reformatted, 4 files left unchanged.

isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /code/src/osc_data_extractor/__init__.py

yamllint.................................................................Failed
- hook id: yamllint
- exit code: 1

.readthedocs.yml
  5:1       warning  missing document start "---"  (document-start)
  12:2      warning  missing starting space in comment  (comments)
  27:8      error    too many spaces inside braces  (braces)
  27:29     error    too many spaces inside braces  (braces)

flake8...................................................................Failed
- hook id: flake8
- exit code: 1

src/osc_data_extractor/__init__.py:4:80: E501 line too long (85 > 79 characters)
src/osc_data_extractor/skeleton.py:12:80: E501 line too long (80 > 79 characters)
src/osc_data_extractor/skeleton.py:16:80: E501 line too long (85 > 79 characters)
src/osc_data_extractor/skeleton.py:75:80: E501 line too long (82 > 79 characters)
src/osc_data_extractor/skeleton.py:81:80: E501 line too long (88 > 79 characters)
src/osc_data_extractor/skeleton.py:109:80: E501 line too long (88 > 79 characters)
src/osc_data_extractor/skeleton.py:114:80: E501 line too long (87 > 79 characters)
src/osc_data_extractor/skeleton.py:116:80: E501 line too long (80 > 79 characters)
src/osc_data_extractor/skeleton.py:131:80: E501 line too long (82 > 79 characters)
src/osc_data_extractor/skeleton.py:133:80: E501 line too long (87 > 79 characters)

mypy.....................................................................Failed
- hook id: mypy
- duration: 1.12s
- exit code: 1

tests/test_skeleton.py:1: error: Cannot find implementation or library stub for module named "pytest"  [import-not-found]
tests/test_skeleton.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 5 source files)
```

**Comment by ModeSevenIndustrialSolutions** [comment]
Contents of .pre-commit-config.yaml below:
```
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-symlinks
      - id: detect-private-key
      - id: check-ast
      - id: debug-statements

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: remove-tabs

  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/s-weigand/flake8-nb
    rev: v0.4.0
    hooks:
      - id: flake8-nb
        additional_dependencies:
          - pep8-naming
        # Ignore all format-related checks as Black takes care of those.
        args:
          - --ignore=E2, W5, F401, E401
          - --select=E, W, F, N
          - --max-line-length=120
```
